from pathlib import Path

COVER = Path("roster_engine/cover_scheduler.py")
PLANNING = Path("roster_engine/planning_generation.py")
PAGE = Path("pages/1_Generate_Roster.py")


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f"Could not find {label}. No files changed.")
    return text.replace(old, new, 1)


cover = COVER.read_text()
planning = PLANNING.read_text()
page = PAGE.read_text()

cover = replace_once(cover, 'def _sessions_conflict(first: str, second: str) -> bool:\n    first = _normalise(first)\n    second = _normalise(second)\n\n    if "FULL_DAY" in {first, second}:\n        return True\n\n    return first == second\n\n\n', 'def _sessions_conflict(first: str, second: str) -> bool:\n    first = _normalise(first)\n    second = _normalise(second)\n\n    if "FULL_DAY" in {first, second}:\n        return True\n\n    return first == second\n\n\ndef cover_owner_centre(\n    requesting_unit: str,\n) -> str | None:\n    import re\n\n    unit = _normalise(requesting_unit)\n\n    if re.match(r"^[A-W]\\s+COY\\b", unit):\n        return "PT"\n\n    if re.match(r"^[1-7](?:ST|ND|RD|TH)?\\s+COY\\b", unit):\n        return "RH"\n\n    return None\n\n\ndef _is_short_cover(slot: DailyCoverSlot) -> bool:\n    return _normalise(slot.session) in {"AM", "PM"}\n\n\ndef _service_type(person: Person) -> str:\n    return _normalise(person.service_type or "")\n\n\ndef _preferred_cover_candidates(\n    *,\n    candidates: list[Person],\n    slot: DailyCoverSlot,\n) -> list[Person]:\n    cbt = [\n        person\n        for person in candidates\n        if _service_type(person) == "CBT"\n    ]\n    if cbt:\n        return cbt\n\n    legacy = [\n        person\n        for person in candidates\n        if _service_type(person) not in {"CBT", "SVC"}\n    ]\n    if legacy:\n        return legacy\n\n    if _is_short_cover(slot):\n        return [\n            person\n            for person in candidates\n            if _service_type(person) == "SVC"\n        ]\n\n    return []\n\n\n', "cover helper section")
cover = replace_once(cover, 'def _candidate_sort_key(\n    *,\n    person: Person,\n    historical_schedule: Schedule | None,\n    locked_duties: list[Assignment],\n    existing_cover_assignments: list[CoverAssignment],\n) -> tuple[float, str]:\n    return (\n        _current_workload_points(\n            person=person,\n            historical_schedule=historical_schedule,\n            locked_duties=locked_duties,\n            existing_cover_assignments=existing_cover_assignments,\n        ),\n        _normalise(person.name),\n    )\n', 'def _candidate_sort_key(\n    *,\n    person: Person,\n    slot: DailyCoverSlot,\n    historical_schedule: Schedule | None,\n    locked_duties: list[Assignment],\n    existing_cover_assignments: list[CoverAssignment],\n) -> tuple[int, float, str]:\n    owner = cover_owner_centre(slot.requesting_unit)\n\n    centre_priority = (\n        0\n        if (\n            owner is not None\n            and _normalise(person.centre) == owner\n        )\n        else 1\n    )\n\n    return (\n        centre_priority,\n        _current_workload_points(\n            person=person,\n            historical_schedule=historical_schedule,\n            locked_duties=locked_duties,\n            existing_cover_assignments=existing_cover_assignments,\n        ),\n        _normalise(person.name),\n    )\n', "cover sort key")
cover = replace_once(cover, '    candidates = sorted(\n        candidates,\n        key=lambda person: _candidate_sort_key(\n            person=person,\n            historical_schedule=historical_schedule,\n            locked_duties=locked_duties,\n            existing_cover_assignments=result.assignments,\n        ),\n    )\n', '    candidates = _preferred_cover_candidates(\n        candidates=candidates,\n        slot=slot,\n    )\n\n    candidates = sorted(\n        candidates,\n        key=lambda person: _candidate_sort_key(\n            person=person,\n            slot=slot,\n            historical_schedule=historical_schedule,\n            locked_duties=locked_duties,\n            existing_cover_assignments=result.assignments,\n        ),\n    )\n', "normal cover selection")
cover = replace_once(cover, '            pool = sorted(\n                pool,\n                key=lambda person: _candidate_sort_key(\n                    person=person,\n                    historical_schedule=historical_schedule,\n                    locked_duties=locked_duties,\n                    existing_cover_assignments=result.assignments,\n                ),\n            )\n', '            pool = _preferred_cover_candidates(\n                candidates=pool,\n                slot=slot,\n            )\n\n            pool = sorted(\n                pool,\n                key=lambda person: _candidate_sort_key(\n                    person=person,\n                    slot=slot,\n                    historical_schedule=historical_schedule,\n                    locked_duties=locked_duties,\n                    existing_cover_assignments=result.assignments,\n                ),\n            )\n', "FC cover selection")

planning = replace_once(planning, 'from roster_engine.cover_scheduler import CoverAssignment, generate_cover_assignments\n', 'from roster_engine.cover_scheduler import (\n    CoverAssignment,\n    cover_owner_centre,\n    generate_cover_assignments,\n)\n', "planning import")
planning = replace_once(planning, 'def generate_roster_from_planning(\n    *,\n    planning: PlanningContext,\n    settings: GenerationSettings,\n    historical_schedule: Schedule | None = None,\n    role_priorities: tuple[RolePriority, ...] | None = None,\n) -> PlanningGenerationResult:\n    rules = planning.roster_rules\n\n    requirements = generate_month_requirements(\n        year=settings.year,\n        month=settings.month,\n        settings=settings.requirement_settings,\n        rules=rules,\n    )\n', 'def _normalise_generation_scope(\n    generation_scope: str,\n) -> str:\n    scope = _normalise(generation_scope)\n    aliases = {\n        "BOTH": "BOTH",\n        "BOTH CENTRES": "BOTH",\n        "PT": "PT",\n        "PT ONLY": "PT",\n        "RH": "RH",\n        "RH ONLY": "RH",\n    }\n\n    if scope not in aliases:\n        raise ValueError(\n            f"Unsupported generation scope: {generation_scope!r}."\n        )\n\n    return aliases[scope]\n\n\ndef _requirement_in_scope(\n    requirement: DutyRequirement,\n    scope: str,\n) -> bool:\n    return (\n        scope == "BOTH"\n        or _normalise(requirement.centre) == scope\n    )\n\n\ndef _cover_slot_in_scope(\n    slot: DailyCoverSlot,\n    scope: str,\n) -> bool:\n    if scope == "BOTH":\n        return True\n\n    return cover_owner_centre(slot.requesting_unit) == scope\n\n\ndef generate_roster_from_planning(\n    *,\n    planning: PlanningContext,\n    settings: GenerationSettings,\n    historical_schedule: Schedule | None = None,\n    role_priorities: tuple[RolePriority, ...] | None = None,\n    generation_scope: str = "BOTH",\n) -> PlanningGenerationResult:\n    rules = planning.roster_rules\n    scope = _normalise_generation_scope(generation_scope)\n\n    all_requirements = generate_month_requirements(\n        year=settings.year,\n        month=settings.month,\n        settings=settings.requirement_settings,\n        rules=rules,\n    )\n\n    requirements = [\n        requirement\n        for requirement in all_requirements\n        if _requirement_in_scope(requirement, scope)\n    ]\n', "planning generation function")
planning = replace_once(planning, '    manual_duties, manual_reserves, manual_covers = (\n        _split_locked_manual_assignments(\n            planning.manual_assignments\n        )\n    )\n\n    locked_duties, remaining_requirements = _apply_locked_duties(\n', '    manual_duties, manual_reserves, manual_covers = (\n        _split_locked_manual_assignments(\n            planning.manual_assignments\n        )\n    )\n\n    if scope != "BOTH":\n        manual_duties = [\n            assignment\n            for assignment in manual_duties\n            if _normalise(assignment.centre or "") == scope\n        ]\n        manual_reserves = [\n            assignment\n            for assignment in manual_reserves\n            if _normalise(assignment.centre or "") == scope\n        ]\n\n    scoped_cover_slots = [\n        slot\n        for slot in planning.cover_slots\n        if _cover_slot_in_scope(slot, scope)\n    ]\n\n    scoped_requirement_ids = {\n        slot.cover_requirement_id\n        for slot in scoped_cover_slots\n        if slot.cover_requirement_id is not None\n    }\n\n    if scope != "BOTH":\n        manual_covers = [\n            assignment\n            for assignment in manual_covers\n            if assignment.cover_requirement_id in scoped_requirement_ids\n        ]\n\n    locked_duties, remaining_requirements = _apply_locked_duties(\n', "planning scope filtering")
planning = replace_once(
    planning,
    "        cover_slots=planning.cover_slots,\n",
    "        cover_slots=scoped_cover_slots,\n",
    "scoped cover slots",
)

page = replace_once(page, 'st.info(\n    "Generation order: locked duties → locked covers/reserves → "\n    "remaining mandatory covers → remaining duties. "\n    "PTMC overnight interest is applied as a soft duty preference."\n)\n\nif st.button(\n', 'st.info(\n    "Generation order: locked duties → locked covers/reserves → "\n    "remaining mandatory covers → remaining duties. "\n    "PTMC overnight interest is applied as a soft duty preference."\n)\n\ngeneration_scope_label = st.radio(\n    "Generation scope",\n    options=[\n        "Both centres",\n        "PT only",\n        "RH only",\n    ],\n    horizontal=True,\n)\n\ngeneration_scope = {\n    "Both centres": "BOTH",\n    "PT only": "PT",\n    "RH only": "RH",\n}[generation_scope_label]\n\nst.caption(\n    "Cover priority: CBT first; correct-centre CBT preferred. "\n    "SVC is used only for AM/PM short covers when CBT cannot fill the slot."\n)\n\nif st.button(\n', "generator scope UI")
page = replace_once(page, '        result = generate_roster_from_planning(\n            planning=planning,\n            settings=GenerationSettings(\n                year=selected_month.year,\n                month=selected_month.month,\n            ),\n        )\n', '        result = generate_roster_from_planning(\n            planning=planning,\n            settings=GenerationSettings(\n                year=selected_month.year,\n                month=selected_month.month,\n            ),\n            generation_scope=generation_scope,\n        )\n', "generator call")

compile(cover, str(COVER), "exec")
compile(planning, str(PLANNING), "exec")
compile(page, str(PAGE), "exec")

for path, new_text in (
    (COVER, cover),
    (PLANNING, planning),
    (PAGE, page),
):
    backup = path.with_suffix(".py.step20b_backup")
    if not backup.exists():
        backup.write_text(path.read_text())
    path.write_text(new_text)

print("Step 20B applied successfully.")
